## Modelo de Clasificación sin pasar por KG

In [12]:
import numpy as np
import pandas as pd
from ampligraph.utils import restore_model
from sklearn import metrics
from xgboost import XGBClassifier

df = pd.read_pickle("../Data/reducedDataset001.pkl")
df["train"] = df.Sujeto > "S14"
model = restore_model("../Data/KGEmbedModel004.pkl")

df.Sujeto = df.Sujeto.values.astype(str)
df.Sujeto = df.Sujeto.str.replace("S","")
df.Sujeto = df.Sujeto.values.astype(np.int64)

In [13]:
x_train = df[df["train"]][["ECG", "EMG", "EDA", "TEMP", "RESP", "Sujeto"]].values
y_train = df[df["train"]]["label"].values
x_test = df[~df["train"]][["ECG", "EMG", "EDA", "TEMP", "RESP", "Sujeto"]].values
y_test = df[~df["train"]]["label"].values

In [14]:
clf_model = XGBClassifier(n_estimators=1000, max_depth=15, objective="multi:softmax")
clf_model.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=15,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=1000, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method=None, validate_parameters=False, verbosity=None)

In [15]:
prediction = clf_model.predict(x_test)
print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test, prediction))

              precision    recall  f1-score   support

           1       0.80      0.72      0.76      3246
           2       0.25      0.08      0.12      1877
           3       0.17      0.07      0.10      1004
           4       0.36      0.71      0.48      2250

    accuracy                           0.50      8377
   macro avg       0.40      0.40      0.36      8377
weighted avg       0.48      0.50      0.46      8377

[[2344    5  336  561]
 [  49  149    0 1679]
 [ 255   76   70  603]
 [ 280  372    0 1598]]
